name: Security Scan

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Run npm audit to check for vulnerabilities in dependencies
      - name: Run npm audit
        run: npm audit --audit-level=high
        continue-on-error: true

      # Run ESLint with security plugins
      - name: Install ESLint and security plugins
        run: |
          npm install --save-dev eslint eslint-plugin-security

      - name: Run ESLint security scan
        run: |
          npx eslint --ext .ts,.js src/ --no-eslintrc -c .github/workflows/eslint-security.json
        continue-on-error: true

      # Run Snyk to check for vulnerabilities
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      # Run custom security check script
      - name: Run custom security check
        run: node security-check.js
        continue-on-error: true

      # Check for secrets in code
      - name: Check for hardcoded secrets
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

      # Upload security scan results as artifacts
      - name: Upload security scan results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            npm-audit.json
            snyk-report.json
            security-check-results.txt
          retention-days: 7